//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextileStore2.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductListForManagerAndClient
    {
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ManufacterValue { get; set; }
        public string StatusValue { get; set; }
        public decimal ProductCost { get; set; }
        public string ProductPhoto { get; set; }
        public string ProductArticleNumber { get; set; }
        public string CategoryValue { get; set; }
        public string ProviderValue { get; set; }
        public string UnitValue { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public Nullable<int> ProductMaxDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
    }
}
